workflows:
  app-store:
    name: Universal App Store Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: braver_search_credentials
    environment:
      groups:
        - certificate_credentials # Contains CERTIFICATE_PRIVATE_KEY
      vars:
        XCODE_PROJECT: "Braver Search/Braver Search.xcodeproj"
        XCODE_SCHEME_IOS: "Braver Search (iOS)"
        XCODE_SCHEME_MACOS: "Braver Search (macOS)"
        BUNDLE_ID: "xyz.bsquared.Braver-Search"
        EXTENSION_BUNDLE_ID: "xyz.bsquared.Braver-Search.Extension"
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: xyz.bsquared.Braver-Search
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: List initial profiles
        script: |
          echo "Initial profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key="$CERTIFICATE_PRIVATE_KEY"
          app-store-connect fetch-signing-files "$EXTENSION_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key="$CERTIFICATE_PRIVATE_KEY"
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_IOS" \
            --archive-flags "-destination 'generic/platform=iOS' -allowProvisioningUpdates"
      - name: Build macOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_MACOS" \
            --archive-flags "-destination 'generic/platform=macOS' -allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/macos/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
