workflows:
  app-store:
    name: Universal App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: latest
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "xyz.bsquared.braversearch"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          keychain initialize
    
    ios_signing:
      distribution_type: app_store
      bundle_identifier: xyz.bsquared.braversearch
    
    macos_signing:
      distribution_type: app_store
      bundle_identifier: xyz.bsquared.braversearch
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
        release_type: manual 