workflows:
  app-store:
    name: Universal App Store Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: braver_search_credentials
    environment:
      vars:
        XCODE_PROJECT: "Braver Search/Braver Search.xcodeproj"
        XCODE_SCHEME_IOS: "Braver Search (iOS)"
        XCODE_SCHEME_MACOS: "Braver Search (macOS)"
        BUNDLE_ID: "xyz.bsquared.Braver-Search"
        EXTENSION_BUNDLE_ID: "xyz.bsquared.Braver-Search.Extension"
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: xyz.bsquared.Braver-Search
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: List initial profiles
        script: |
          echo "Initial profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Set up certificates and profiles
        script: |
          # Create distribution certificate
          echo "Creating distribution certificate..."
          CERT_INFO=$(app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --save \
            --certificates-dir ~/certificates)
          echo "$CERT_INFO"
          
          # Get the certificate ID
          CERT_ID=$(echo "$CERT_INFO" | grep -o '"id":"[^"]*"' | cut -d'"' -f4)
          echo "Certificate ID: $CERT_ID"
          
          # Get the bundle ID resource ID
          echo "Getting bundle ID resource..."
          BUNDLE_ID_INFO=$(app-store-connect bundle-ids list --json | grep -B 2 "$EXTENSION_BUNDLE_ID")
          echo "$BUNDLE_ID_INFO"
          
          # Create the profile
          echo "Creating profile..."
          app-store-connect create-profile \
            --type IOS_APP_STORE \
            --bundle-id "$EXTENSION_BUNDLE_ID" \
            --certificate-ids "$CERT_ID" \
            --name "Braver Search iOS Extension App Store"
            
          echo "After creating extension profile:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_IOS" \
            --archive-flags "-destination 'generic/platform=iOS' -allowProvisioningUpdates"
      - name: Build macOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_MACOS" \
            --archive-flags "-destination 'generic/platform=macOS' -allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/macos/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
