workflows:
  app-store:
    name: Universal App Store Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: braver_search_credentials
    environment:
      vars:
        XCODE_PROJECT: "Braver Search/Braver Search.xcodeproj"
        XCODE_SCHEME_IOS: "Braver Search (iOS)"
        XCODE_SCHEME_MACOS: "Braver Search (macOS)"
        BUNDLE_ID: "xyz.bsquared.Braver-Search"
        EXTENSION_BUNDLE_ID: "xyz.bsquared.Braver-Search.Extension"
      xcode: latest
      ios_signing:
        profile: "app_store"
        provisioning_profiles:
          - bundle_identifier: xyz.bsquared.Braver-Search
            provisioning_profile: "Braver Search iOS App Store"
          - bundle_identifier: xyz.bsquared.Braver-Search.Extension
            provisioning_profile: "Braver Search iOS Extension App Store"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Codemagic CLI Tools
        script: pip3 install codemagic-cli-tools
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_IOS" \
            --archive-flags "-destination 'generic/platform=iOS' CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=A947N6H5GS"
      - name: Build macOS App
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME_MACOS" \
            --archive-flags "-destination 'generic/platform=macOS' CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=A947N6H5GS"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/macos/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true 
