name: App Store Deployment (Raw)

on:
  # workflow_run:
  #   workflows: ["Test"]
  #   types:
  #     - completed
  #   branches: [main]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: macos-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Import Certificate
        env:
          DEVELOPMENT_CERTIFICATE_BASE64: ${{ secrets.DEVELOPMENT_CERTIFICATE_BASE64 }}
          DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: temporary
          IOS_APP_DEVELOPMENT_PROFILE_BASE64: ${{ secrets.IOS_APP_DEVELOPMENT_PROFILE_BASE64 }}
          IOS_EXT_DEVELOPMENT_PROFILE_BASE64: ${{ secrets.IOS_EXT_DEVELOPMENT_PROFILE_BASE64 }}
          MACOS_APP_DEVELOPMENT_PROFILE_BASE64: ${{ secrets.MACOS_APP_DEVELOPMENT_PROFILE_BASE64 }}
          MACOS_EXT_DEVELOPMENT_PROFILE_BASE64: ${{ secrets.MACOS_EXT_DEVELOPMENT_PROFILE_BASE64 }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain

          # Import development certificate
          echo $DEVELOPMENT_CERTIFICATE_BASE64 | base64 --decode > development.p12
          security import development.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          rm development.p12

          # Import distribution certificate
          echo $DISTRIBUTION_CERTIFICATE_BASE64 | base64 --decode > distribution.p12
          security import distribution.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          rm distribution.p12

          # Create provisioning profiles directories
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles

          # Install iOS development profiles
          echo "$IOS_APP_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/ios_app_development.mobileprovision
          echo "$IOS_EXT_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/ios_ext_development.mobileprovision
          
          # Also install in new Xcode location
          echo "$IOS_APP_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/ios_app_development.mobileprovision
          echo "$IOS_EXT_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/ios_ext_development.mobileprovision

          # Install macOS development profiles
          echo "$MACOS_APP_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/macos_app_development.provisionprofile
          echo "$MACOS_EXT_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/macos_ext_development.provisionprofile
          
          # Also install in new Xcode location
          echo "$MACOS_APP_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/macos_app_development.provisionprofile
          echo "$MACOS_EXT_DEVELOPMENT_PROFILE_BASE64" | base64 --decode > ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/macos_ext_development.provisionprofile

          # Set permissions
          sudo chown -R $USER:staff ~/Library/MobileDevice/Provisioning\ Profiles/
          sudo chown -R $USER:staff ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/

          # Update keychain search list
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Set up App Store Connect API
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APPLE_API_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8

      - name: Build iOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (iOS)" \
            -configuration Release \
            -archivePath build/ios/BraverSearch.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Development" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain"

          # Create exportOptions.plist for iOS
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF

          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/BraverSearch.xcarchive \
            -exportPath build/ios \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

      - name: Build macOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (macOS)" \
            -configuration Release \
            -archivePath build/macos/BraverSearch.xcarchive \
            -destination "generic/platform=macOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Development" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain"

          # Create exportOptions.plist for macOS
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF

          # Export APP
          xcodebuild -exportArchive \
            -archivePath build/macos/BraverSearch.xcarchive \
            -exportPath build/macos \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

      - name: Upload to TestFlight
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        run: |
          # Upload iOS build
          xcrun altool --upload-app --type ios \
            --file "build/ios/BraverSearch.ipa" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID"
          
          # Upload macOS build
          xcrun altool --upload-app --type osx \
            --file "build/macos/BraverSearch.app" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID" 

      - name: Clean up secrets
        if: always()
        run: |
          rm -f ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8