name: App Store Deployment (Raw)

on:
  # workflow_run:
  #   workflows: ["Test"]
  #   types:
  #     - completed
  #   branches: [main]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  MARKETING_VERSION: "1.0"
  BASE_BUILD_NUMBER: ${{ vars.BUILD_NUMBER || 1 }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: macos-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean workspace
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ./**/xcuserdata
          rm -rf ./**/*.xcodeproj/project.xcworkspace/xcuserdata
          rm -rf ./**/*.xcodeproj/xcuserdata
          rm -rf build/

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Set iOS version numbers
        run: |
          cd "Braver Search"
          
          echo "Using build number: $BASE_BUILD_NUMBER"
          
          # Set marketing version
          agvtool new-marketing-version "$MARKETING_VERSION"
          
          # Set iOS build number
          agvtool new-version -all $BASE_BUILD_NUMBER
          
          # Update manifest.json version
          major_version=$(echo "$MARKETING_VERSION" | cut -d. -f1)
          minor_version=$(echo "$MARKETING_VERSION" | cut -d. -f2)
          manifest_version="$major_version.$minor_version.0"
          echo "Setting manifest version to $manifest_version"
          sed -i '' "s/\"version\": \"[^\"]*\"/\"version\": \"$manifest_version\"/" "Shared (Extension)/Resources/manifest.json"
          
          cd ..

      - name: Import Certificate
        env:
          DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
          MAC_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.MAC_INSTALLER_CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: temporary
          IOS_APP_PROFILE_BASE64: ${{ secrets.IOS_APP_PROFILE_BASE64 }}
          IOS_EXT_PROFILE_BASE64: ${{ secrets.IOS_EXT_PROFILE_BASE64 }}
          MACOS_APP_PROFILE_BASE64: ${{ secrets.MACOS_APP_PROFILE_BASE64 }}
          MACOS_EXT_PROFILE_BASE64: ${{ secrets.MACOS_EXT_PROFILE_BASE64 }}
        run: |
          # Create variables
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import distribution certificate
          CERTIFICATE_PATH=$RUNNER_TEMP/distribution.p12
          echo $DISTRIBUTION_CERTIFICATE_BASE64 | base64 --decode -o $CERTIFICATE_PATH
          security import $CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          rm $CERTIFICATE_PATH

          # Import Mac Installer Distribution certificate
          MAC_CERTIFICATE_PATH=$RUNNER_TEMP/mac_installer.p12
          echo $MAC_INSTALLER_CERTIFICATE_BASE64 | base64 --decode -o $MAC_CERTIFICATE_PATH
          security import $MAC_CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          rm $MAC_CERTIFICATE_PATH

          # Create provisioning profiles directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          # Install iOS App Store profiles
          echo "$IOS_APP_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_iOS_App_Store.mobileprovision
          echo "$IOS_EXT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_iOS_Extension_App_Store.mobileprovision

          # Install macOS App Store profiles
          echo "$MACOS_APP_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_macOS_App_Store.provisionprofile
          echo "$MACOS_EXT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_macOS_Extension_App_Store.provisionprofile

          # Set permissions
          sudo chown -R $USER:staff ~/Library/MobileDevice/Provisioning\ Profiles/

          # Set key partition list
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # List keychains
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Set up App Store Connect API
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APPLE_API_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8

      - name: Build iOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (iOS)" \
            -configuration Release \
            -archivePath build/ios/BraverSearch.xcarchive \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            "Braver Search (iOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search iOS App Store" \
            "Braver Search Extension (iOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search iOS Extension App Store" \
            OTHER_CODE_SIGN_FLAGS="--keychain $RUNNER_TEMP/app-signing.keychain-db" \
            ENABLE_BITCODE=NO

          # Create exportOptions.plist for iOS
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>xyz.bsquared.Braver-Search</key>
                  <string>Braver Search iOS App Store</string>
                  <key>xyz.bsquared.Braver-Search.Extension</key>
                  <string>Braver Search iOS Extension App Store</string>
              </dict>
          </dict>
          </plist>
          EOF

          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/BraverSearch.xcarchive \
            -exportPath build/ios \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

          # List build directory contents for debugging
          echo "iOS build directory contents:"
          ls -R build/ios/

      - name: Increment build number for macOS
        run: |
          # Increment build number for macOS
          NEW_BUILD_NUMBER=$((BASE_BUILD_NUMBER + 1))
          echo "BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV

      - name: Set macOS version numbers
        run: |
          cd "Braver Search"
          
          # Keep same marketing version as iOS
          agvtool new-marketing-version "$MARKETING_VERSION"
          
          # Use incremented build number for macOS
          echo "Using macOS build number: $BUILD_NUMBER"
          agvtool new-version -all $BUILD_NUMBER
          
          cd ..

      - name: Build macOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (macOS)" \
            -configuration Release \
            -archivePath build/macos/BraverSearch.xcarchive \
            -destination 'platform=macOS,arch=arm64' \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            "Braver Search (macOS):PRODUCT_BUNDLE_IDENTIFIER=xyz.bsquared.Braver-Search" \
            "Braver Search Extension (macOS):PRODUCT_BUNDLE_IDENTIFIER=xyz.bsquared.Braver-Search.Extension" \
            "Braver Search (macOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search macOS App Store" \
            "Braver Search Extension (macOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search macOS Extension App Store" \
            OTHER_CODE_SIGN_FLAGS="--keychain $RUNNER_TEMP/app-signing.keychain-db"

          # Create exportOptions.plist for macOS
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>installerSigningCertificate</key>
              <string>3rd Party Mac Developer Installer</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>xyz.bsquared.Braver-Search</key>
                  <string>Braver Search macOS App Store</string>
                  <key>xyz.bsquared.Braver-Search.Extension</key>
                  <string>Braver Search macOS Extension App Store</string>
              </dict>
          </dict>
          </plist>
          EOF

          # Export APP
          xcodebuild -exportArchive \
            -archivePath build/macos/BraverSearch.xcarchive \
            -exportPath build/macos \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates \
            -verbose

      - name: Increment build number for next run
        run: |
          # Increment build number for next run
          NEXT_BUILD=$((BUILD_NUMBER + 1))
          echo "NEXT_BUILD_NUMBER=$NEXT_BUILD" >> $GITHUB_ENV

      - name: Upload to TestFlight
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        run: |
          echo "Checking build directories:"
          echo "iOS build directory:"
          ls -la build/ios/
          echo "macOS build directory:"
          ls -la build/macos/

          # Find the IPA file
          IPA_PATH=$(find build/ios -name "*.ipa" -type f)
          if [ -z "$IPA_PATH" ]; then
            echo "Error: No IPA file found in build/ios directory"
            exit 1
          fi
          echo "Found IPA at: $IPA_PATH"

          # Upload iOS build
          echo "Uploading iOS build..."
          xcrun altool --upload-app --type ios \
            --file "$IPA_PATH" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID" \
            --verbose

          # Find the APP file
          APP_PATH=$(find build/macos -name "*.pkg" -type f)
          if [ -z "$APP_PATH" ]; then
            echo "Error: No PKG file found in build/macos directory"
            exit 1
          fi
          echo "Found APP at: $APP_PATH"
          
          # Upload macOS build
          echo "Uploading macOS build..."
          xcrun altool --upload-app --type osx \
            --file "$APP_PATH" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID" \
            --verbose

      - name: Clean up secrets
        if: always()
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*
          rm -f ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8

      - name: Update GitHub build number variable
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X PATCH /repos/${{ github.repository }}/actions/variables/BUILD_NUMBER \
            -f value="$NEXT_BUILD_NUMBER" \
            || gh api -X POST /repos/${{ github.repository }}/actions/variables \
               -f name="BUILD_NUMBER" \
               -f value="$NEXT_BUILD_NUMBER"