name: App Store Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'Braver Search/**'
      - '.github/workflows/app-store.yml'
      - 'fastlane/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-build-deploy:
    name: Test, Build and Deploy
    runs-on: macos-latest
    
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up code signing
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}
        run: |
          # Create temporary keychain
          KEYCHAIN_NAME="github_actions_keychain"
          KEYCHAIN_PASSWORD="temporary_password"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -t 3600 -l "$KEYCHAIN_NAME"

          # Import certificate
          echo "$CERTIFICATE_PRIVATE_KEY" > certificate_key.pem
          security import certificate_key.pem -k "$KEYCHAIN_NAME" -T /usr/bin/codesign
          
          # Set up App Store Connect API
          echo "$APPLE_API_PRIVATE_KEY" > appstore_key.p8
          mkdir -p ~/.fastlane
          cat > ~/.fastlane/app_store_connect_api_key.json << EOF
          {
            "key_id": "$APPLE_API_KEY_ID",
            "issuer_id": "$APPLE_API_KEY_ISSUER_ID",
            "key": "$(cat appstore_key.p8)"
          }
          EOF

          # Clean up sensitive files
          rm certificate_key.pem appstore_key.p8

      - name: Run iOS lane
        run: bundle exec fastlane ios beta
        env:
          MATCH_KEYCHAIN_NAME: github_actions_keychain
          MATCH_KEYCHAIN_PASSWORD: temporary_password

      - name: Run macOS lane
        run: bundle exec fastlane mac beta
        env:
          MATCH_KEYCHAIN_NAME: github_actions_keychain
          MATCH_KEYCHAIN_PASSWORD: temporary_password 