name: App Store Deployment (Raw)

on:
  # workflow_run:
  #   workflows: ["Test"]
  #   types:
  #     - completed
  #   branches: [main]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: macos-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up keychain
        env:
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.APPLE_CERTIFICATE_PRIVATE_KEY }}
          IOS_APP_PROFILE_BASE64: ${{ secrets.IOS_APP_PROFILE_BASE64 }}
          IOS_EXT_PROFILE_BASE64: ${{ secrets.IOS_EXT_PROFILE_BASE64 }}
          MACOS_APP_PROFILE_BASE64: ${{ secrets.MACOS_APP_PROFILE_BASE64 }}
          MACOS_EXT_PROFILE_BASE64: ${{ secrets.MACOS_EXT_PROFILE_BASE64 }}
        run: |
          # Create keychain
          KEYCHAIN_NAME="build.keychain"
          KEYCHAIN_PASSWORD="temporary"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -t 3600 -l "$KEYCHAIN_NAME"

          # Import certificate
          echo "$CERTIFICATE_PRIVATE_KEY" > certificate_key.pem
          security import certificate_key.pem -k "$KEYCHAIN_NAME" -T /usr/bin/codesign
          rm certificate_key.pem
          
          # Create provisioning profiles directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          # Install iOS profiles
          echo "$IOS_APP_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_iOS_App_Store.mobileprovision
          echo "$IOS_EXT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_iOS_Extension_App_Store.mobileprovision
          
          # Install macOS profiles
          echo "$MACOS_APP_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_macOS_App_Store.provisionprofile
          echo "$MACOS_EXT_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Braver_Search_macOS_Extension_App_Store.provisionprofile

      - name: Set up App Store Connect API
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
        run: |
          # Create private_keys directory
          mkdir -p ~/.appstoreconnect/private_keys
    
          # Store API key
          echo "$APPLE_API_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8

      - name: Verify App Store Connect API credentials
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        run: |
          # Store API key
          xcrun altool --list-apps \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID"

      - name: Build iOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (iOS)" \
            -configuration Release \
            -archivePath build/ios/BraverSearch.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            "Braver Search (iOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search iOS App Store" \
            "Braver Search Extension (iOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search iOS Extension App Store"

          # Create exportOptions.plist
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>xyz.bsquared.Braver-Search</key>
                  <string>Braver Search iOS App Store</string>
                  <key>xyz.bsquared.Braver-Search.Extension</key>
                  <string>Braver Search iOS Extension App Store</string>
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF

          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/BraverSearch.xcarchive \
            -exportPath build/ios \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

      - name: Build macOS App
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Archive
          xcodebuild archive \
            -project "Braver Search/Braver Search.xcodeproj" \
            -scheme "Braver Search (macOS)" \
            -configuration Release \
            -archivePath build/macos/BraverSearch.xcarchive \
            -destination "generic/platform=macOS" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            "Braver Search (macOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search macOS App Store" \
            "Braver Search Extension (macOS):PROVISIONING_PROFILE_SPECIFIER=Braver Search macOS Extension App Store"

          # Create exportOptions.plist
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>xyz.bsquared.Braver-Search</key>
                  <string>Braver Search macOS App Store</string>
                  <key>xyz.bsquared.Braver-Search.Extension</key>
                  <string>Braver Search macOS Extension App Store</string>
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF

          # Export APP
          xcodebuild -exportArchive \
            -archivePath build/macos/BraverSearch.xcarchive \
            -exportPath build/macos \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

      - name: Upload to TestFlight
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        run: |
          # Upload iOS build
          xcrun altool --upload-app --type ios \
            --file "build/ios/BraverSearch.ipa" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID"
          
          # Upload macOS build
          xcrun altool --upload-app --type osx \
            --file "build/macos/BraverSearch.app" \
            --apiKey "$APPLE_API_KEY_ID" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID" 

      - name: Clean up secrets
        if: always()
        run: |
          rm -f ~/.appstoreconnect/private_keys/AuthKey_${APPLE_API_KEY_ID}.p8