name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-swift:
    name: Swift Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Show Available Xcode Versions
      run: ls -la /Applications/Xcode*
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
      
    - name: Show Selected Xcode
      run: xcode-select -p
      
    - name: Build and Test iOS
      run: |
        cd "Braver Search"
        xcodebuild test \
          -project "Braver Search.xcodeproj" \
          -scheme "Braver Search (iOS)" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
          -enableCodeCoverage YES
          
    - name: Build and Test macOS
      run: |
        cd "Braver Search"
        xcodebuild test \
          -project "Braver Search.xcodeproj" \
          -scheme "Braver Search (macOS)" \
          -destination 'platform=macOS,arch=arm64' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        xcode: true
        
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test
      
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage