name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-swift:
    name: Swift Tests
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
    - name: List Directory Contents
      run: ls -la
      
    - name: Build and Test
      working-directory: ./Braver Search
      run: |
        xcodebuild test \
          -scheme "Braver Search" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -enableCodeCoverage YES
          
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        xcode: true
        
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test
      
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage 